config/routes.rb
Rails.application.routes.draw do
  
  
  # Defines the root path route ("/")
  root "sessions#home"
  # devise_for :users
  devise_for :users, controllers: { sessions: 'users/sessions' }  
 
 
  # user related 
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  get '/users/:id', to: 'users#show'
  
  resources :tour_companies do 
    resources :destinations 
      
  end
  #session routes
  # get '/login', to: 'sessions#login'
  # post '/login', to: 'sessions#create'
  # post '/logout', to: 'sessions#destroy'
  # get '/logout', to: 'sessions#destroy'

end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :tour_company
  has_one_attached :main_image
  has_one :destination_detail, dependent: :destroy
  accepts_nested_attributes_for :tour_company
  accepts_nested_attributes_for :destination_details
  # converting the location into a Hash by serializing
  # serialize :location, type: Hash, coder: YAML
  # store :location, accessors: [:city,:state,:country,:country_code], coder: JSON, prefix: true
  # validates :dest_name, presence: true
  # validates :location_city, presence: true
  # validates :rating, presence: true
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: %i[ show edit update destroy ]

  
  # GET /destinations or /destinations.json
  def index
    puts 
    puts "the params are #{params}"
    @destinations = Destination.where(tour_company_id: current_user.tour_company.id )
    puts "The output is #{@destinations}"
  end

  # GET /destinations/1 or /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
  
    @destination = current_user.tour_company.destination.build
    # puts "The destination value is: #{@destination.build}"
    @user_now = current_user
        
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations or /destinations.json
  def create
    @destination = current_user.tour_company.destination.build(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to tour_company_destinations_url(@destination), notice: "Destination was successfully created." }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1 or /destinations/1.json
  def update
    @destination = Destination.find(params[:id])
    puts "THe dest is #{@destination}"
    puts "The params is #{params.inspect}"
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to tour_company_destinations_url(@destination.tour_company, @destination), notice: "Destination was successfully updated." }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1 or /destinations/1.json
  def destroy
    @destination.destroy!

    respond_to do |format|
      format.html { redirect_to tour_company_destinations_url, notice: "Destination was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
   def destination_params
    params.require(:destination).permit(:id, :dest_name, :rating, :main_image, :tour_company_id, location: [:location_city, :location_state, :location_country, :location_country_code])
   end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
    # def parse_json(destination)
    #     destination.location ? puts YAML.load(destination.location) : "No"
    #     return destination.location ? JSON.parse(destination.location) : "Not set yet"
    # end
end

app/views/destinations/_destination.html.erb
<div id="<%= dom_id destination %>">
  <p>
    <strong>Dest name:</strong>
    <%= destination.dest_name %>
  </p>

  <p>
    <strong>Location:</strong>
    <ul>
      <li><%= destination.location ?  JSON.parse(destination.location.gsub("=>",":"))["location_city"]: "No"%></li>
      <li><%= destination.location ?  JSON.parse(destination.location.gsub("=>",":"))["location_state"]: "No"%></li>
      <li><%= destination.location ?  JSON.parse(destination.location.gsub("=>",":"))["location_country"]: "No"%></li>
      <li><%= destination.location ?  JSON.parse(destination.location.gsub("=>",":"))["location_country_code"]: "No"%></li>
      
    </ul>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= destination.rating %>
  </p>

  <p>
    <strong>Main photo:</strong>
   <% if destination.main_image.attached? %>
     <%= image_tag destination.main_image.variant(resize_to_limit: [150, nil]) %>
   <% else %>
     No photo yet. Pls update now!
   <% end %>
  </p>

  <p>
    <strong>Tour company:</strong>
    <%= destination.tour_company_id %>
  </p>

</div>

app/views/destinations/_form.html.erb
<%= form_with model: @destination, url: tour_company_destinations_path(@destination.tour_company_id, @destination) do |form| %>
  <% if @destination.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
        <% @destination.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dest_name, style: "display: block" %>
    <%= form.text_field :dest_name, :required => true %>
  </div>

  <div>
     <%= form.fields_for :location do |f|%>
      <%= f.label :location_city, style: "display: block" %>
      <%= f.text_field :location_city  ,:required => true %>

      <%= f.label :location_state, style: "display: block" %>
      <%= f.text_field :location_state ,:required => true %>

      <%= f.label :location_country, style: "display: block" %>
      <%= f.text_field :location_country ,:required => true %>

      <%= f.label :location_country_code, style: "display: block" %>
      <%= f.text_field :location_country_code ,:required => true %>
    <% end %>
    
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating, :required => true %>
  </div>

  <div>
    <%= form.label :main_photo, style: "display: block" %>
    <%= form.file_field :main_image, :required => true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render "layouts/updateForm", destination: @destination %>

<br>

<div>
  <%= link_to "Show this destination", tour_company_destination_path(@destination.tour_company, @destination) %> |
  <%= link_to "Back to destinations", tour_company_destinations_path %>
</div>

app/views/destinations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Destinations</h1>

<div id="destinations">
  <% @destinations.each do |destination| %>
    <%= render destination %>
    <p>
      <%= link_to "Show this destination", tour_company_destination_path(destination.tour_company, destination) %>
    </p>
  <% end %>
</div>
<br><br>
<%= link_to "New destination", new_tour_company_destination_path %>
<%= link_to "Back to your profile", tour_companies_path %>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render "form", destination: @destination %>

<br>

<div>
  <%= link_to "Back to destinations", tour_company_destinations_path %>
</div>

app/views/destinations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @destination %>

<div>
  <%= link_to "Edit this destination", edit_tour_company_destination_path(@destination.tour_company,@destination) %> |
  <%= link_to "Back to destinations", tour_company_destinations_path %>

  <%= button_to "Destroy this destination", tour_company_destination_path(@destination.tour_company, @destination), method: :delete %>
</div>